### ISSUE TITLE
Trying to get in touch

### ISSUE THREAD

**Issue by skade** [angeloashmore/angeloashmore.com#1]
Hi Angelo,

this might be an odd way, but I can't find a way to get in touch with you. Your website seems to be dead. I'm a @padrinorb alumni and would like to talk to you about your FOSS website designs (in detail, I want to adopt one). I find them some of the most cleanest and workable for FOSS project pages. Both the rom-rb and padrino site bear no license, though, so I'd be interested if you have any conditions.

Could you send me a message, either on Twitter (@argorak) or via email (flo@andersground.net)?

Best,
Florian

**Comment by angeloashmore** [comment]
Hi @skade! I just sent you a message on Twitter.

**Comment by skade** [comment]
Thanks, feel free to delete this message :).
